
# this is a test 1 in DEV 
POST https://ahri4fkpmd.execute-api.ap-southeast-1.amazonaws.com/dev/c360-profile-track HTTP/1.1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Content-Type: application/json
Accept: application/json

{
  "schema_version": "2025.04.28",
  "event_id": "5ed708ca-a682-4c26-969b-5c339554b5ea",
  "tenant_id": "PNJ",
  "datetime": "2025-05-06T04:00:00Z",
  "unix_timestamp": 1746529570870,
  "metric": "identify",
  "visid": "9b02723f-2dcb-440b-8498-532331d76e9e",
  "mediahost": "www.pnj.com.vn",
  "tpurl": "https://www.pnj.com.vn/",
  "profile_traits": {
    "phone_number": "860000316623",
    "first_name": "Thomas",
    "last_name": "Nguyen",
    "gender": "male",
    "date_of_birth": "1990-05-21",
    "email": "trieu@example.com",
    "source_system": "website",
    "address_line1": "Phu Lam B",
    "state": "Hochiminh City",
    "ext_attributes": {
      "loyalty_level": "gold"
    }
  }
}
