
# this is a test 2 in stagging 
POST https://ahri4fkpmd.execute-api.ap-southeast-1.amazonaws.com/dev/c360-profile-track HTTP/1.1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Content-Type: application/json
Accept: application/json

{
    "schema_version": "2025.04.28",
    "event_id": "5ed708ca-a682-4c26-969b-5c339554b5ea",
    "tenant_id": "PNJ",
    "datetime": "2025-05-06T04:00:00Z",
    "unix_timestamp": 1746529570870,
    "metric": "identify",

    "mediahost": "www.pnj.com.vn",
    "tpurl": "https://www.pnj.com.vn/",
    "profile_traits": 
    {
        "phone_number": "840903122291",
        "first_name": "Trieu",
        "last_name": "Nguyen",
        "gender": "male",
        "date_of_birth": "1986-08-16",
        "email": "trieu@example.com",
        "source_system": "ecommerce",
        "address_line1": "Phu Lam B",
        "city": "Hochiminh City",
        "ext_attributes": 
        {
            "voucher_code": "FB2025-HELLO",
            "referrer": "facebook",
            "store_id": "store_001",
            "source": "offline_redeem",
            "loyalty_level": "gold"   
        }
    }
}