
# this is a test in stagging 
POST https://ahri4fkpmd.execute-api.ap-southeast-1.amazonaws.com/dev/c360-profile-track HTTP/1.1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Content-Type: application/json
Accept: application/json

{
  "schema_version": "2025.04.28",
  "event_id": "5ed708ca-a682-4c26-969b-5c339554b5ea",
  "tenant_id": "PNJ",
  "datetime": "2025-05-06T04:00:00Z",
  "unix_timestamp": 1746529570870,
  "metric": "identify",
  "visid": "2b02723f-2dcb-440b-8498-532331d76e8e",
  "mediahost": "www.pnj.com.vn",
  "tpurl": "https://www.pnj.com.vn/",
  "profile_traits": {
    "phone": "0903122290",
    "lastname": "Dương",
    "firstname": "Jane",
    "gender": "female",
    "dob": "1983-12-19",
    "loyalty_level": "bronze",
    "email": "jane50@example.net",
    "metadata": {
      "referrer": "facebook_ad"
    }
  },
  "utmdata": {
    "utmsource": "google",
    "utmmedium": "video",
    "utmcampaign": "womens_day",
    "utmterm": "jewelry+sale",
    "utmcontent": "video_ad_03"
  }
}
