
# this is a test in stagging 
POST https://ahri4fkpmd.execute-api.ap-southeast-1.amazonaws.com/dev/c360-profile-track HTTP/1.1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
content-type: application/json
accept: application/json

{
  "schema_version": "2025.02.28",
  "event_id": "e5f67891-1234-5678-9abc-3213131",
  "tenant_id": "PNJ",
  "datetime": "2025-04-28T10:13:00.000Z",
  "unix_timestamp": 1740737580000,
  "metric": "login",
  "visid": "c4d5e6f7-8901-2345-6789-abcdef012345",
  "mediahost": "www.pnj.com.vn",
  "tpurl": "https://www.pnj.com.vn/",
  "profile_traits": {
    "customer_id": "CUST7890",
    "phone": "0903122290",
    "firstname": "Trieu",
    "tax_id": "0316233152"
  },
  "utmdata": {
    "utmsource": "vnexpress",
    "utmmedium": "cpc",
    "utmcampaign": "promo-campaign",
    "utmterm": "discount",
    "utmcontent": "banner1"
  }
}